# Generated by Django 6.0.2 on 2026-03-22 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='diningtable',
            options={'ordering': ['restaurant', 'code']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='diningtable',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.AddField(
            model_name='diningtable',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='table_type',
            field=models.CharField(choices=[('normal', 'Bàn thường'), ('vip', 'Bàn VIP')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_type',
            field=models.CharField(choices=[('normal', 'Bàn thường'), ('vip', 'Bàn VIP')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='status',
            field=models.CharField(choices=[('available', 'Còn trống'), ('reserved', 'Đã đặt'), ('occupied', 'Đang phục vụ'), ('cleaning', 'Đang dọn')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
