# Generated by Django 6.0.2 on 2026-05-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('food_type', models.CharField(choices=[('mon_an', 'Món ăn'), ('do_uong', 'Đồ uống'), ('combo', 'Combo/Buffet'), ('dich_vu', 'Dịch vụ'), ('che_bien', 'Hàng chế biến')], default='mon_an', max_length=30)),
                ('price', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('max_stock', models.PositiveIntegerField(default=999)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Đang kinh doanh'), ('inactive', 'Ngừng kinh doanh'), ('out_of_stock', 'Hết hàng')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
    ]
