# Generated by Django 6.0.2 on 2026-05-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workshift_employeeperformance_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
