# Generated by Django 6.0.2 on 2026-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_employee_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
    ]
