# Generated by Django 6.0.2 on 2026-05-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employee_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('table_type', models.CharField(choices=[('normal', 'Bàn thường'), ('vip', 'VIP')], max_length=20)),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('available', 'Trống'), ('reserved', 'Đã đặt'), ('occupied', 'Đang dùng'), ('cleaning', 'Đang dọn')], default='available', max_length=20)),
                ('pos_x', models.IntegerField(default=50)),
                ('pos_y', models.IntegerField(default=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('guests', models.IntegerField(default=2)),
                ('booking_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('confirmed', 'Đã duyệt'), ('late', 'Tới trễ'), ('cancelled', 'Huỷ bàn'), ('completed', 'Hoàn thành')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.restauranttable')),
            ],
        ),
    ]
